# Q1

In [1]:
import pandas as pd

df = pd.read_csv('q1/click_event_log.csv')
df.head()

ImportError: No module named pandas

In [2]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack
from sklearn.metrics import confusion_matrix

ohe_user = OneHotEncoder()
ohe_ad = OneHotEncoder()
user_features = ohe_user.fit_transform(df['user_id'].reshape((-1, 1)))
ad_features = ohe_ad.fit_transform(df['ad_id'].reshape((-1, 1)))
X = hstack([user_features, ad_features]).todense()

y = df['clicked_on_ad'].values

In [3]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, oob_score=True)
clf.fit(X, y)

predictions = clf.predict(X)
print("OOB score: {}".format(clf.oob_score_))
print(confusion_matrix(y, predictions))

OOB score: 0.8344
[[4241    9]
 [  58  692]]


a. Given a user_id and an ad_id, create a model that will predict the probability that the user will click on the ad. List any assumptions you make about the data when you create this model. What does this model output for user_id 12 and ad_id 10? What about user_id 50 and ad_id 177? Finally, what about user_id 13 and ad_id 241?

In [30]:
import numpy as np

users = np.array([12, 50, 13]).reshape((-1, 1)) - 1
ads = np.array([10, 177, 241]).reshape((-1, 1)) - 1

user_features = ohe_user.transform(users)
ad_features = ohe_ad.transform(ads)
features = hstack([user_features, ad_features]).todense()

clf.predict(features)

array([0, 0, 0], dtype=int64)

# Q2

In [33]:
df = pd.read_csv('q2/satelite_20.csv')

In [34]:
df.head()

log_azimuth  log_altitiude  lens_size  months_in_operation  \
0     2.351222       2.996789   8.041122                    1   
1     2.379440       3.050773   5.448220                    3   
2     2.441207       3.071607   2.134721                    3   
3     2.454324       3.127072   7.271947                    1   
4     2.465330       3.162127   6.854447                    0   

   observed_image_output  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0

In [43]:
from collections import Counter

Counter(df['observed_image_output'])

Counter({0: 51, 1: 51, 2: 51})

In [48]:
from sklearn.ensemble import RandomForestClassifier

X = df.drop('observed_image_output', axis=1).values
y = df['observed_image_output']

clf = RandomForestClassifier(n_estimators=100, oob_score=True)
clf.fit(X, y)

predictions = clf.predict(X)
print("OOB score: {}".format(clf.oob_score_))
print(confusion_matrix(y, predictions))

OOB score: 0.732026143791
[[51  0  0]
 [ 0 51  0]
 [ 0  0 51]]


In [57]:
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import StratifiedKFold

# Deprecated

In [4]:
from sklearn import naive_bayes

clf = naive_bayes.BernoulliNB()
clf.fit(X, y)

predictions = clf.predict(X)
confusion_matrix(y, clf.predict(X))

array([[4247,    3],
       [ 742,    8]])

In [6]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X, y)

predictions = clf.predict(X)
print(confusion_matrix(y, predictions))

[[4248    2]
 [ 745    5]]
