# Q1

In [1]:
import pandas as pd

df = pd.read_csv('q1/click_event_log.csv')
df.head()

user_id  ad_id  clicked_on_ad
0       20    308              0
1       35    270              0
2       36    168              0
3       21    479              0
4       86    321              0

In [3]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack
from sklearn.metrics import confusion_matrix

ohe = OneHotEncoder()
user_features = ohe.fit_transform(df['user_id'].reshape((-1, 1)))
ad_features = ohe.fit_transform(df['ad_id'].reshape((-1, 1)))
X = hstack([user_features, ad_features]).todense()

y = df['clicked_on_ad'].values

In [4]:
from sklearn import naive_bayes

clf = naive_bayes.BernoulliNB()
clf.fit(X, y)

predictions = clf.predict(X)
confusion_matrix(y, clf.predict(X))

array([[4247,    3],
       [ 742,    8]])

In [7]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, oob_score=True)
clf.fit(X, y)

predictions = clf.predict(X)
print("OOB score: {}".format(clf.oob_score_))
print(confusion_matrix(y, predictions))

OOB score: 0.8328
[[4245    5]
 [  62  688]]


In [6]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X, y)

predictions = clf.predict(X)
print(confusion_matrix(y, predictions))

[[4248    2]
 [ 745    5]]
